---
# This is a special case, all other workflows in this repo are templates for reusing
name: Publish THIS to GitHub
run-name: Publish THIS to GitHub
on:
  workflow_dispatch:
  push:

jobs:
  Publish-To-Github:
    uses: https://github.com/james9001/james9001-workflows/.gitea/workflows/github-publish.yaml@020dd083a4173acd0c0270e2da95ba28ca54f35e
    with:
      github_user_name: james9001
      github_user_email: james9001@james9001.net
      github_repo_owner: james9001
    secrets:
      GITHUB_USER_CREDENTIALS: ${{ secrets.JAMES9001_GITHUB_CREDENTIALS }}
