---
name: Publish to GitHub
run-name: Publish to GitHub
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Publish-To-Github:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to GitHub
        run: |
          git config --global credential.helper store
          git config --global user.name james9001
          git config --global user.email james9001@james9001.net
          echo "${{ secrets.JAMES9001_GITHUB_CREDENTIALS }}" > /root/.git-credentials
          git remote add github https://github.com/james9001/${{ github.event.repository.name }}.git
          git push github
