---
name: Snyk Code Check (Go 1.24)
run-name: Snyk Code Check (Go 1.24)
on:
  workflow_call:
    secrets:
      SNYKTOKEN:
        required: true

jobs:
  Snyk-Code-Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Run Snyk (Go 1.24)
        run: |
          docker run --rm \
            -e SNYK_TOKEN=${{ secrets.SNYKTOKEN }} \
            -v ${{ env.JOB_CONTAINER_NAME }}:/app \
            snyk/snyk:golang-1.24 snyk test \
            --severity-threshold=high
